spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/burgerStation
    username: postgres
    password: 04071982
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: burger_station
        format_sql: true
    hibernate:
      ddl-auto: update
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
logging:
  level:
    org:
      hibernate:
        SQL: ERROR
      type:
        descriptor:
          sql:
            BasicBinder: ERROR

#server.error.include-message=always
#spring.web.resources.cache.cachecontrol.max-age=369d

